server:
  port: 9001
spring:
  application:
    name: tensquare-base  # 微服务名称，如果只有单个微服务，服务名称没用。在服务间调用的时候，服务名称非常有用！！！
  datasource: #数据源
    url: jdbc:mysql://192.168.12.100:3306/tensquare_base?characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa: # jpa的参数
    show-sql: true  # 是否打印sql
    generate-ddl: true # 是否自动建表
    database: mysql
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true